# Generated by Django 2.2.5 on 2019-10-13 21:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('phase2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='location',
            new_name='city',
        ),
        migrations.AddField(
            model_name='branch',
            name='address',
            field=models.CharField(default='Houston', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='state',
            field=models.CharField(default='TX', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='zipcode',
            field=models.PositiveIntegerField(default=77002),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(default='New Hire', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
